\# exec: groff isonline.man -Tascii -man | less
\#
\# .TH cmd-name section [date [version [page-descr]]]
.TH files 1 "23 Nov 2019" "v1.0" "User Commands"
.SH NAME
files \- do something with files
.SH SYNOPSIS
\# .SY command; .OP \-df...; .OP \-d cs; .OP \-f fam; ...; .RI [ parameter .\|.\|. ]; .YS;
.SY files
.RI [ ... ]
.OP \-x ...
.OP \-e ...
.OP \-h
.OP \-v
.YS
.SH DESCRIPTION
files [patterns [-x exclude-patterns [-e execute-commands]]]
.SH OPTIONS
.TP
.BR \-x
list of excluded patterns
.TP
.BR \-e
list of commands to execute
.TP
.BR \-h
Help screen
.TP
.BR \-v
Program information (version, license, ...)
\#
\# .SH SEE ALSO
\# command1(section), command2(section)
.SH AUTHOR
.MT nereus@\:freemail.gr
Nicholas Christopoulos
.ME
.br
.UR https://github.com/nereusx/unix-utils
Prject page:
.UE
\# EOF
