\# exec: groff dof.1 -Tascii -man | less
\#
\# .TH cmd-name section [date [version [page-descr]]]
.TH dof 1 "17 Dec 2019" "v1.7" "User Commands"
.SH NAME
dof \- (do-for) executes commands for each item of a list
.SH SYNOPSIS
\# .SY command; .OP \-efp...; .OP \-d cs; .OP \-f fam; ...; .RI [ parameter .\|.\|. ]; .YS;
.SY dof
.OP \-efpr
.OP \-s N..N\fR[\fB..N\fR]
.OP \-l
.OP \-h
.OP \-v
.RI [item\ ...\ |\ -\ ]
.RI [ \fB\-x\fR\ ...]
.RI [ \fB\-g\fR\ ...]
.RI \fBdo\fR\ [\ command\ |\ -\ ]
.SH DESCRIPTION
\fIdof\fR executes commands for each item (file or string) of a list
.PP
.EX
	# convert all mp3s to ogg
	dof -e *.mp3 do ffmpeg -i "%f" "%b.ogg"
	
	# display colors on terminal
	dof -e -s:0..15 do 'tput setaf %f; echo colour%f; tput op;'
	
	# remove all files except *.pdf and *.tex
	dof -e * -g *.{pdf,tex} do 'rm %f'
.EE
.SH OPTIONS
.TP
.BR \-
Read from stdin.
.TP
.BR \-e
Execute; \fIdof\fR displays what commands would be run, this option executes them.
.TP
.BR \-x
Exclude list; after \fB-x\fR are following glob's patterns to exclude items from the previous list.
When the pattern is unquoted it will expanded by the shell otherwise `glob()' will be used in each directory.
See
.BR glob (3)
.TP
.BR \-g
Exclude list; after \fB-g\fR are following regex's patterns to exclude items from the previous list.
Since the \fIdof\fR parameters can be anything, this is no glob file-patterns but regex's patterns.
Example `*.c' file-pattern should be written as `.*\\.c'.
.TP
.BR \-r
Recursive execution into subdirectories. You have to be sure that you type wildcard patterns quoted,
otherwise the wildcards will expanded by the shell in the first directory.
.TP
.BR \-f
Force non-stop; \fIdof\fR stops on error (exit code != 0), this option forces \fIdof\fR to ignore them.
.TP
.BR \-p
Plain files only; directories, devices, etc are ignored.
.TP
.BR \-d
Directories only; plain-files, devices, etc are ignored.
.TP
.BR \-s F..L[..S]
Adds a sequence of numbers (float or integer).
\fIF\fR for first, \fIL\fR for last and optionally \fIS\fR for step.
This option can be repeated many times.
.TP
.BR \-l
Print recipes (/etc/dof.conf, ~/.dof)
.TP
.BR \-\-\fIrecipe\fR
Execute recipe (ex: dof --to-ogg)
.TP
.BR \-h
Help screen.
.TP
.BR \-v
Version and license information.
.SH VARIABLES
In the `commands' you can use several program's variables. Variables are recognized by prefix '%'.
Variables and its modifiers can be included inside '{' '}' block or '(' ')' block.
.TP
.BR %f
The full string (or filename)
.TP
.BR %b
The basename (no directory, no extension)
.TP
.BR %d
The dirname (only the directory without the '/' suffix) 
.TP
.BR %e
The extension without '.' prefix
.TP
.BR %%
The character '%'.
.SH MODIFIERS
Modifiers defined by ':' that follows a variable and modifies the result string.
You can have unlimited number of modifiers.
.TP
.BR l\fIc...\fR
Returns the string until the the first occurence of character 'c'.
.TP
.BR r\fIc...\fR
Returns the string until the last occurence of character 'c'.
.TP
.BR i\fIs\fR
Returns the string until the occurence of string 's'.
\# .TP
\# .BR %(expr)
\# string processing expression... not used yet.
.SH FILES
\fBdof\fR reads `\fI/etc/dof.conf\fR' and `\fI~/.dof\fR' files.
These files contains recipes in form `name: parameters'.
These recipes can later executed with \fB--\fIname\fR option.
.PP
Example:
.EX
	to-ogg: *.wav *.mp3 do 'ffmpeg -i "%f" "%b.ogg" && rm "%f"'
	to-png: *.jpg *.gif do 'convert "%f" "%b.png" && rm "%f"'
.EE
.SH NOTES
.TP
Items '.' and '..' are ignored.
.SH SEE ALSO
.BR glob (3),
.BR regex (7)
.PP
.SH AUTHOR
.MT nereus@\:freemail.gr
Nicholas Christopoulos
.ME
.br
.UR https://github.com/nereusx/unix-utils
Project page:
.UE
\# EOF
