\# exec: groff dof.1 -Tascii -man | less
\#
\# .TH cmd-name section [date [version [page-descr]]]
.TH dof 1 "12 Mar 2019" "v1.0" "User Commands"
.SH NAME
dof \- (do-for) executes commands for each item of a list
.SH SYNOPSIS
\# .SY command; .OP \-efp...; .OP \-d cs; .OP \-f fam; ...; .RI [ parameter .\|.\|. ]; .YS;
.SY dof
.OP \-efp
.OP \-l
.OP \-h
.OP \-v
.RI [item .\|.\|. | - ]\ do\ [ command | - ]
.SH DESCRIPTION
\fIdof\fR executes commands for each item (file or string) of a list
.PP
Example, convert all mp3s to ogg
.EX
	dof -e *.mp3 do ffmpeg -i %f %b.ogg
.EE
.SH OPTIONS
.TP
.BR \-
read from stdin.
.TP
.BR \-e
execute; \fIdof\fR displays what commands would be run, this option executes them.
.TP
.BR \-f
force non-stop; \fIdof\fR stops on error (exit code != 0), this option forces \fIdof\fR to ignore them.
.TP
.BR \-p
plain files only; directories, devices, etc are ignored.
.TP
.BR \-d
directories only; plain-files, devices, etc are ignored.
.TP
.BR \-l
print recipes (/etc/dof.conf, ~/.dof)
.TP
.BR \-\-\fIrecipe\fR
execute recipe (ex: dof --to-ogg)
.TP
.BR \-h
help screen.
.TP
.BR \-v
version and license information.
.SH VARIABLES
In the `commands' you can use several program's variables. Variables are recognized by prefix '%'.
.TP
.BR %f
the full string (or filename)
.TP
.BR %b
the basename (no directory, no extension)
.TP
.BR %d
the dirname (only the directory without the '/' suffix) 
.TP
.BR %e
the extension without '.' prefix
.TP
.BR %%
the character '%'.
.TP
.BR %(expr)
string processing expression... not used yet.
.SH FILES
dof reads \fI/etc/dof.conf\fR and \fI~/.dof\fR files.
These files contains recipes in form `name: parameters'.
These recipes can later executed with \fB--\fIname\fR option.
.PP
Example:
.EX
	to-ogg: *.mp3 do ffmpeg -i %f %b.ogg
	to-png: *.{jpg,gif} do convert %f %b.png
.EE
.SH NOTES
.TP
Items '.' and '..' are ignored.
\# .SH SEE ALSO
\# command1(section), command2(section)
.SH AUTHOR
.MT nereus@\:freemail.gr
Nicholas Christopoulos
.ME
.br
.UR https://github.com/nereusx/unix-utils
Prject page:
.UE
\# EOF
