\# exec: groff isonline.man -Tascii -man | less
\#
\# .TH cmd-name section [date [version [page-descr]]]
.TH isonline 1 "22 Nov 2019" "v1.0" "User Commands"
.SH NAME
isonline \- returns the internet connection status
.SH SYNOPSIS
\# .SY command; .OP \-df...; .OP \-d cs; .OP \-f fam; ...; .RI [ parameter .\|.\|. ]; .YS;
.SY isonline
.OP \-p
.OP \-q
.OP \-h
.OP \-v
.RI [ ip-address \ or\  hostname ]
.YS
.SH DESCRIPTION
Sends an ICMP echo request to a specified server or its default server
and displays 'yes' or 'no' if its responds.
Returns 0 if the server responds.
.SH OPTIONS
.TP
.BR \-p
Prints additional information as the IP and the time to respond.
.TP
.BR \-q
Display nothing; just return the exit code.
.TP
.BR \-h
Help screen
.TP
.BR \-v
Program information (version, license, ...)
\#
\# .SH SEE ALSO
\# command1(section), command2(section)
.SH AUTHOR
.MT nereus@\:freemail.gr
Nicholas Christopoulos
.ME
.br
.UR https://github.com/nereusx/unix-utils
Project page:
.UE
\# EOF
